config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root "contracts#index"
  end
  root "home#index"

  authenticate :user do
      resources :equipment, only: [:index, :show, :new, :create, :edit, :update]
      resources :prices, only: [:index, :new, :create]
      resources :delivery_receipt, only: [:show]
      resources :customers, only: [:index, :show, :new, :create, :edit, :update]
      resources :proposals, only: [:index]

      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :devolution_receipts, only: [:show, :new, :create]

        member do
          put 'close', to: 'contracts#close'
          post 'delivery_receipt', to: 'contracts#create_delivery_receipt'
        end
      end
  end

  resources :proposals, only: [:show, :new, :create]
end

app/models/contract.rb
class Contract < ApplicationRecord
  validates :contract_number,
            :customer_id,
            :shipping_address,
            :rental_period_id,
            :shipping_contact,
            :date_begin,
            :date_end,
            :discount, presence: true

  before_validation :calc_date_end
  before_save       :calc_price,
                    :set_initial_status,
                    :set_equipment_unavailable

  belongs_to :customer
  belongs_to :rental_period
  has_many   :rented_equipment
  has_many   :equipment, through: :rented_equipment
  has_one    :devolution_receipt
  has_one    :delivery_receipt

  def total_value
    price - discount if price
  end

  def close
    update(status: 'Encerrado')
    set_equipment_available
  end

  private

  def calc_price
    total = 0
    equipment.each do |equip|
      price = Price.find_by(equipment: equip, rental_period: rental_period)
      total += price.try(:amount).to_f
    end
    self.price = total
  end

  def calc_date_end
    self.date_end = date_begin + rental_period.period if rental_period
  end

  def set_initial_status
    self.status ||= 'Em aberto'
  end

  def set_equipment_unavailable
    equipment.each(&:unavailable!)
  end

  def set_equipment_available
    equipment.each(&:available!)
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :close]

  def index
    @contracts = Contract.all
  end

  def show
  end

  def new
    set_collection
    @equipment = Equipment.where(status: [:available])
  end

  def create
    @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to @contract
    else
      flash.now[:notice] = 'Não foi possível emitir contrato'
      @equipment = Equipment.where(status: [:available])
      render :new
    end
  end

  def edit
  end

  def close
    @contract.close
    redirect_to @contract
  end

  def create_delivery_receipt
    @contract = Contract.find(params[:id])
    @contract.create_delivery_receipt
    redirect_to @contract.delivery_receipt
  end

  private

  def contract_params
    params.require(:contract).permit(:contract_number,
                                     :order_number, :customer_id,
                                     :shipping_address, :shipping_contact,
                                     :rental_period_id,
                                     :date_begin, :discount,
                                     equipment_ids: [])
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end

  def set_collection
    @contract = Contract.new
    @customers = Customer.all
    @periods = RentalPeriod.all
  end
end

app/views/contracts/index.html.erb
<section>
  <h1>Lista de Contratos</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Número Contrato</th>
        <th>Cliente</th>
        <th>Endereço Entrega</th>
        <th>Contato Entrega</th>
        <th>Data início</th>
        <th>Período</th>
        <th>Valor total</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.contract_number %></td>
        <td><%= contract.customer.name %></td>
        <td><%= contract.shipping_address %></td>
        <td><%= contract.shipping_contact %></td>
        <td><%= l(contract.date_begin) %></td>
        <td><%= contract.rental_period.description %></td>        
        <td><%= number_to_currency(contract.total_value) %></td>
        <td><%= contract.status %></td>
        <td><%= link_to 'Detalhes', contract, class: "btn btn-default btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>
<div><%= link_to 'Voltar', root_path , class: "btn btn-default" %></div>

app/views/contracts/new.html.erb
<section>
  <h1>Novo Contrato</h1>
  <%= simple_form_for @contract do |f| %>
    <%= f.input :contract_number, label: 'Número do contrato' %>
    <%= f.input :order_number, label: 'Número do pedido' %>
    <%= f.input :customer_id, label: 'Cliente',
                                   collection: @customers %>
    <%= f.input :shipping_contact, label: 'Contato de entrega' %>
    <%= f.input :shipping_address, label: 'Endereço de entrega' %>
    <%= f.input :date_begin, label: 'Data de início', as: :date %>
    <%= f.input :rental_period_id, label: 'Prazo de locação',
                                   collection: @periods, label_method: :description %>
    <%= f.association :equipment, collection: @equipment, label_method: :description, value_method: :id %>
    <%= f.input :discount, label: 'Desconto', class: "form-control", input_html: { value: '0' } %>
    <%= link_to 'Voltar', root_path , class: "btn btn-default" %>
    <%= f.button :submit, 'Emitir contrato' %>
  <% end %>
</section>

app/views/contracts/show.html.erb
<section>
  <h1><%= @contract.contract_number %></h1>
  <dl class="dl-horizontal">
    <dt>Numero do Pedido</dt>
    <dd><%= @contract.order_number %></dd>
    <dt>Nome do Cliente</dt>
    <dd><%= @contract.customer.name %></dd>
    <dt>Endereço de Entrega</dt>
    <dd><%= @contract.shipping_address %></dd>
    <dt>Contato</dt>
    <dd><%= @contract.shipping_contact %></dd>
    <dt>Periodo de Locação</dt>
    <dd><%= @contract.rental_period.description %></dd>
    <dt>Equipamentos Alugados</dt>
    <% @contract.equipment.each do |equipment| %>
      <dd><%= equipment.description %></dd>
    <% end %>
    <dt>Inicio da Locação</dt>
    <dd><%= l(@contract.date_begin) %></dd>
    <dt>Fim da locação</dt>
    <dd><%= l(@contract.date_end) %></dd>
    <dt>Valor Total</dt>
    <dd><%= number_to_currency(@contract.price) %></dd>
    <dt>Desconto</dt>
    <dd><%= number_to_currency(@contract.discount) %></dd>
    <dt>Valor a ser pago</dt>
    <dd><%= number_to_currency(@contract.total_value)%></dd>
    <dt>Status</dt>
    <dd><%= @contract.status %></dd>
  </dl>
  <div>
    <%= link_to 'Voltar', root_path , class: "btn btn-default" %>
    <% if @contract.status != 'Encerrado' %>
      <%= link_to 'Encerrar contrato', close_contract_path(@contract) , method: :put, class: "btn btn-danger" %>
    <% else %>
      <a href="#" class="btn btn-success disabled">Contrato encerrado</a>
    <% end %>
    <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Recibos <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <% if @contract.delivery_receipt %>
            <%= link_to 'Visualizar Recibo de Entrega', delivery_receipt_path(@contract.delivery_receipt) %>
          <% else %>
            <%= link_to 'Gerar Recibo de Entrega', delivery_receipt_contract_path(@contract), method: :post %>
          <% end %>
        </li>
        <li>
          <% if @contract.devolution_receipt %>
            <%= link_to "Vizualizar Recibo de Devolução", contract_devolution_receipt_path(@contract) %>
          <% else %>
            <%= link_to "Gerar Recibo de Devolução", new_contract_devolution_receipt_path(@contract) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</section>