config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root "contracts#index"
  end
  root "home#index"

  authenticate :user do
      resources :equipment, only: [:index, :show, :new, :create, :edit, :update]
      resources :prices, only: [:index, :new, :create]
      resources :delivery_receipt, only: [:show]
      resources :customers, only: [:index, :show, :new, :create, :edit, :update]
      resources :proposals, only: [:index]

      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :devolution_receipts, only: [:show, :new, :create]

        member do
          put 'close', to: 'contracts#close'
          post 'delivery_receipt', to: 'contracts#create_delivery_receipt'
        end
      end
  end

  resources :proposals, only: [:show, :new, :create]
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :code,
            :name,
            :document,
            :billing_address,
            :billing_city,
            :billing_state,
            :billing_zipcode,
            :financial_contact,
            presence: true

  has_many :contracts
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update]
  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      flash[:notice] = 'Não foi possivel criar o cliente'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      flash[:notice] = 'Não foi possível atualizar esse cliente'
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer)
          .permit(:code, :name, :document, :billing_address,
                  :billing_city, :billing_state,
                  :billing_zipcode, :financial_contact)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/views/customers/edit.html.erb
<section>
  <%= simple_form_for @customer do |f| %>
    <%= f.input :code, label: 'Código do cliente' %>
    <%= f.input :name, label: 'Razão Social' %>
    <%= f.input :document, label: 'CPF/CNPJ' %>
    <%= f.input :billing_address, label: 'Endereço de cobrança' %>
    <%= f.input :billing_city, label: 'Cidade' %>
    <%= f.input :billing_state, label: 'Estado' %>
    <%= f.input :billing_zipcode, label: 'CEP' %>
    <%= f.input :financial_contact, label: 'Contato Financeiro' %>

    <%= link_to 'Voltar', root_path , class: "btn btn-default" %>
    <%= f.button :submit, 'Atualizar' %>
  <% end %>
</section>

app/views/customers/index.html.erb
<section>
  <h1>Lista de Clientes</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Code</th>
        <th>Razão Social</th>
        <th>CPF/CNPJ</th>
        <th>Endereço de cobrança</th>
        <th>Contato financeiro</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.code %></td>
        <td><%= link_to customer.name, customer %></td>
        <td><%= customer.document %></td>
        <td>
        <%= "#{customer.billing_address} -
            #{customer.billing_city}/#{customer.billing_state}" %>
        </td>
        <td><%= customer.financial_contact %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>
<div><%= link_to 'Voltar', root_path , class: "btn btn-default" %></div>

app/views/customers/new.html.erb
<section>
  <%= simple_form_for @customer do |f| %>
    <%= f.input :code, label: 'Código do cliente' %>
    <%= f.input :name, label: 'Razão Social' %>
    <%= f.input :document, label: 'CPF/CNPJ' %>
    <%= f.input :billing_address, label: 'Endereço de cobrança' %>
    <%= f.input :billing_city, label: 'Cidade' %>
    <%= f.input :billing_state, label: 'Estado' %>
    <%= f.input :billing_zipcode, label: 'CEP' %>
    <%= f.input :financial_contact, label: 'Contato Financeiro' %>

    <%= link_to 'Voltar', root_path , class: "btn btn-default" %>
    <%= f.button :submit, 'Criar Cliente' %>
  <% end %>
</section>

app/views/customers/show.html.erb
<section>
  <h1><%= @customer.name %></h1>
  <dl class="dl-horizontal">
    <dt>Código do cliente</dt>
    <dd><%= @customer.code %></dd>
    <dt>Razão Social</dt>
    <dd><%= @customer.name %></dd>
    <dt>CPF/CNPJ</dt>
    <dd><%= @customer.document %></dd>
    <dt>Endereço de Cobrança</dt>
    <dd><%= @customer.billing_address %></dd>
    <dt>Cidade</dt>
    <dd><%= @customer.billing_city %></dd>
    <dt>Estado</dt>
    <dd><%= @customer.billing_state %></dd>
    <dt>CEP</dt>
    <dd><%= @customer.billing_zipcode %></dd>
    <dt>Contato Financeiro</dt>
    <dd><%= @customer.financial_contact %></dd>
  </dl>
  <div>
    <%= link_to 'Voltar', customers_path , class: "btn btn-default" %>
    <%= link_to 'Editar', edit_customer_path(@customer) , class: "btn btn-primary" %>  
  </div>
</section>