config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root "contracts#index"
  end
  root "home#index"

  authenticate :user do
      resources :equipment, only: [:index, :show, :new, :create, :edit, :update]
      resources :prices, only: [:index, :new, :create]
      resources :delivery_receipt, only: [:show]
      resources :customers, only: [:index, :show, :new, :create, :edit, :update]
      resources :proposals, only: [:index]

      resources :contracts, only: [:index, :show, :new, :create, :edit, :update] do
        resources :devolution_receipts, only: [:show, :new, :create]

        member do
          put 'close', to: 'contracts#close'
          post 'delivery_receipt', to: 'contracts#create_delivery_receipt'
        end
      end
  end

  resources :proposals, only: [:show, :new, :create]
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "RafaEquip", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Visualizar Orçamentos", proposals_path %>
            </li>
            <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contratos<span class="caret"></span></a>
             <ul class="dropdown-menu" role="menu">
               <li>
                 <%= link_to "Visualizar Contratos", contracts_path %>
               </li>
               <li>
                 <%= link_to "Novo Contrato", new_contract_path %>
               </li>
             </ul>
           </li>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Visualizar Clientes", customers_path %>
                </li>
                <li>
                  <%= link_to "Novo Cliente", new_customer_path %>
                </li>
              </ul>
            </li>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Equipamentos<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Visualizar Equipamentos", equipment_index_path %>
                </li>
                <li>
                  <%= link_to "Novo Equipamento", new_equipment_path %>
                </li>
              </ul>
            </li>

            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Preços<span class="caret"></span></a>
               <ul class="dropdown-menu" role="menu">
                 <li>
                   <%= link_to "Tabela de Preços", prices_path %>
                 </li>
                 <li>
                   <%= link_to "Novo Preço", new_price_path %>
                 </li>
               </ul>
             </li>

            <% else %>
            <li>
              <%= link_to "Orçamento", new_proposal_path %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right">
            Olá, <strong><%= current_user.email %></strong>
          </p>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>Rafaequip</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <%= render 'layouts/header' %>

        <div class="container">
            <% if notice %>
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <p><%= notice %></p>
            </div>
            <% end %>

            <% if alert %>
            <div class="alert alert-warning" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <p><%= alert %></p>
            </div>
            <% end %>

            <%= yield %>
        </div>
    </body>
</html>